### ISSUE TITLE
left_join causing duplicated columns

### ISSUE THREAD

**Issue by conig** [Motivation-and-Behaviour/sleepIPD_analysis#15]
Looks like the left_join has caused duplicated vars.

```
> names(data_holdout)[grepl("age\\.", names(data_holdout))]
[1] "age.x" "age.y"
```

Do we need the left_join or can we use base indexing?
e.g., 

```
data_clean[study_id %in% ids, ]
```

etc

**Comment by tarensanders** [comment]
You need the combination of `studyid` and `filename` (the `studyid` is the study it comes from, `filename` the file that was processed). Can you do that just with base indexing?

**Comment by tarensanders** [comment]
But yeah, the duplicated columns is a problem I can fix.

**Comment by conig** [comment]
> u need the combination of `studyid` and `filename` (the `studyid` is the study it comes from, `filename` the file that was processed). Can you do that just with base indexing?

Oh I see, I thought we were just splitting by study_id at the end of the day.

To do with base R indexing would need a row variable which could have been pulled in the pipe

```
data$rowid <- seq_len(nrow(data))
data<- data[rowid %in% ids,]
```

I have a little bit of fear about joins when using big(ish) data as they will happily duplicate rows/cols silently which can be hard to detect. In one proj I even created safe_leftjoin which caused errors if nrows changed. Almost got stung once in data-linkage proj, thankfully caught it.
