### ISSUE TITLE
Assessing moderation for research Question 1 and 2

### ISSUE THREAD

**Issue by conig** [Motivation-and-Behaviour/sleepIPD_analysis#54]
> We will examine both main effects and subpopulation effects (using separate models), including the following pre-specified individual-level moderators; age (chronological), body mass index z-score (z transformed), SES, ethnicity, and sex as categorical. Day of the week, season (summer vs winter), geographic location, and daylight length will also be included as moderators because these influence sleep and physical activity. Accelerometer wear location will be included as a moderator. Sleep and physical activity may be temporally related where early morning and late evening physical activity can negatively influence optimum sleep duration and sleep quality. To account for this, we will include the time of the day corresponding to the most active periods of physical activity as a moderator. The most active 60, 30, 15, 10 and 5 minutes within 4 windows of time; midnight to 6am (early), 6am to 12pm (normal), 12pm -6pm (normal), 6pm -midnight (late) will be extracted from GGIR and used to test the effect of physical activity proximity to bedtime and wake time on sleep.

For these moderations, I will test whether the curvilinear relationship, and the linear relationship changes based on moderator values (this also includes main effects when run in R).
```
{outcome} ~ {x} * {moderator} + I({x}^2) * {moderator}
```

## Moderator inclusion
We decided that not all moderators needed to be assessed in a single paper (this would be far too many models to describe). However, all these analyses should be done at some point, or put in supplementary materials.

**We can track progress and decisions by editing the following table:**

| Moderator                                          | Status| var | Done |
|----------------------------------------------------|-----------------------------------------------|:----:|:----:|
|1. Age (chronological)                                |                                                   |  age|  ✓   |
|2. Body mass index z-score (z transformed)           |                                                      |bmi |  ✓   |
|3. Socioeconomic status (SES)                         |                                                     |ses  |  ✓   |
|4. Ethnicity                                          |  Ethnicity was removed because it could not be harmonised | **MISSING**  |  ✗   |
|5. Sex (categorical)                                  |                                                      | sex |  ✓   |
|6. Day of the week                                    |                                                      | weekday_x |  ✓   |
|7. Season (summer vs winter)                          |                                                      | season |  ✓   |
|8. Geographic location                                 |    | region |  ✓   |
|9. Daylight length                                    |                                                      | daylight_hours  |  ✓   |
|10. Accelerometer wear location                        |                                                      | accelerometer_wear_location |  ✓   |
|11. Time of the day corresponding to most active periods of physical activity |                            | **MISSING** |  ✓   |

**Comment by conig** [comment]
@tarensanders I've implemented everything in the current dataset (#49). Could we review if ethnicity really cannot be harmonised. Even if it just because 'white' vs non-white which some authors did, maybe that's better than nothing for protocol compliance.

Also can we extract the time of the day corresponding to the most activbe period of phsycial activity?
> The most active 60, 30, 15, 10 and 5 minutes within 4 windows of time; midnight to 6am (early), 6am to 12pm (normal), 12pm -6pm (normal), 6pm -midnight (late) will be extracted from GGIR and used to test the effect of physical activity proximity to bedtime and wake time on sleep.

**Comment by tarensanders** [comment]
Try doing it by largest groups.
