### ISSUE TITLE
Testing for bidirectional relationships, confirming approach. Have we covered this? Do we need to perform SEM?

### ISSUE THREAD

**Issue by conig** [Motivation-and-Behaviour/sleepIPD_analysis#56]
> We will test for bidirectional associations (Research Question 3) and nonlinear relationships when exploring the association between physical activity and sleep variables. This may include the use of generalised additive models, if appropriate.

We currently do this simply by usnig two sets of regressions

`Excercise -> sleep`
and
`previous_sleep -> excercise`

Therefore, by answering research question 1, and research question 2, we answer reseach question 3.

We need to confirm we are going to lock this in. Note this does not use [generalised additive models](https://www.youtube.com/watch?v=sgw4cu8hrZM) as is briefly mentioned in the protocol. Do we know who suggested GAMs?

GAMs look great for non-linearity but I can't see how they are going to help with bidirectionality.
Example:

```
library(targets)
library(mgcv)
library(tidymv)

library(ggplot2)

tar_load(data_holdout)

model <- gam(sleep_duration ~ s(pa_volume, by = sex) + sex, data = data_holdout)

predict_gam(model) |> 
  ggplot(aes(pa_volume, fit)) +
  geom_point(data = data_holdout, aes(x = pa_volume, y = sleep_duration, colour = sex), alpha = 0.01) +
  geom_smooth_ci(sex) +
  theme_bw() + labs(y = "Sleep duration", x = "PA volume") +
  guides(colour = "none")
```

![image](https://user-images.githubusercontent.com/12742211/226242637-58ce1eb0-2ffc-4b23-87cf-83e64843cbf6.png)

**Comment by conig** [comment]
We need to discuss if GAMs help us handle RQ3, over what we already have. It seems to me like they serve the same funciton as the polynomial equations.

**Comment by tarensanders** [comment]
So I don't know why it says GAMs. 

I think we are already testing for bi-directionality by specifying the model in both directions. Since it's not the same variables (because of the lag/lead thing) this isn't just reverse causality. If both models are significant, that's an indicator for bi-directionality. This is what one of our PhD students did, and there were no concerns in peer-review (which is a low bar, I know).

When I mentioned this to Chris, he suggested SEM (because of course he did, he's a psych). It would look something like:

```mermaid
flowchart LR
    PA1 --> PA2 & Sleep1
    PA2 --> PA3 & Sleep2
    PA3 --> PA4 & Sleep3
    PA4 --> Sleep4
    Sleep1 --> PA2 & Sleep2
    Sleep2 --> PA3 & Sleep3
    Sleep3 --> PA4 & Sleep4
```

I don't really know if we need to do this though, since it's not what we said in the protocol.

**Comment by conig** [comment]
I think we can take this one back to the team once Tim organises. I agree that SEM makes sense for the aim. But we suggested this right at the beginning, and I remember some were concerned that the journals we are targeting may not be familiar with SEM.

**Comment by conig** [comment]
If we were going to do this we'd only be able to include a few cycles as half the sample only has three recorded measurement days
```
> data_clean$measurement_day |> gsub(".*_","", x = _ ) |>  as.numeric() |> quantile(na.rm = TRUE)
  0%  25%  50%  75% 100% 
   0    1    3    6  116 
```

**Comment by tarensanders** [comment]
Let me double check those very high measurement day values. Those are suspect.

**Comment by tarensanders** [comment]
There's some cases where a row has no PA data *and* no sleep data. That seems crazy. Just waiting on the new imputations to finish then I'll push a fix. It might also smooth out those remaining bumps in the imputations.

**Comment by tarensanders** [comment]
@conig satisfied that we can close this? We can let the reviewers decide if we need a different approach.

**Comment by conig** [comment]
Yes I agree, closed.
