### ISSUE TITLE
Use of intensity gradients for physical activity?

### ISSUE THREAD

**Issue by conig** [Motivation-and-Behaviour/sleepIPD_analysis#57]
> The intensity gradient that we will use to model associations with sleep and intensity of physical activity is calculated using 24 hours of time and therefore includes time spent asleep

We are using per-day observations. Is this possible to do?

**Comment by conig** [comment]
From what I can gather this is the origin of the `pa_intensity` variable. Sounds like the protocol is calling for more granula intensity? Or am I misinterpreting?

**Comment by tarensanders** [comment]
I'm not 100% sure why this sentence is in there, other than to indicate that it *might* be correlated with sleep (but seems pretty unlikely - you'd have to have some very long sleep and some very short sleep for it to matter). I don't think there's any action needed here, beyond #59 and #58.

BTW, correlated at 0.8 so I don't think this is going to matter much.
