### ISSUE TITLE
Testing variance inflation factor to assess whether time-spent asleep has affected the intensity metric 

### ISSUE THREAD

**Issue by conig** [Motivation-and-Behaviour/sleepIPD_analysis#58]
> We will test multicollinearity, including testing the variance inflation factor to ensure that including time spent asleep in the intensity metric does not negatively impact results.

Is this relevant for how we have estimated `pa_intensity` from accelerometer data.

**Comment by conig** [comment]
@tarensanders did we make a decision on this one?

**Comment by tarensanders** [comment]
Yeah, I was just finding it a PITA to get it out of the pooled model. Let me take another look at it.

**Comment by conig** [comment]
@tarensanders can we close this? Or is this still something that needs doing?

**Comment by tarensanders** [comment]
@conig Urgh I'd forgotten about this.

I'm not totally sure what it was we were saying we would do here. I think we're saying that the time spent asleep was included in the calculation for the intensity metric, but the way to test if that matters would be comparing models with different measures of the intensity metric, right? (One with sleep, one without)

We didn't calculate PA intensity - it comes out of GGIR. So I'd have to redo the variable by hand to make it work. I think we're way past that point. I'd be happy to kick for touch and revisit if a reviewer thinks this is a mistake.

What are your thoughts?

**Comment by conig** [comment]
That sounds like a lot of work for a minor point. I don't think we want to get in the business of validating GGIR's algorithms, it seems out of scope for the current paper. Let's close for now and see what the reviews say.
