### ISSUE TITLE
Implement CoDA

### ISSUE THREAD

**Issue by conig** [Motivation-and-Behaviour/sleepIPD_analysis#60]
> We will also use CoDA to explore and compare the time-use relationship between the different physical behaviours during the 24-hour day (Research Questions 1-2). For this purpose, we will use a 4-part composition representing the relative amounts of time spent in sleep, sedentary behaviour, light, and moderate to vigorous intensity physical activity. Age appropriate cut-points will be applied (Hildebrand et al 2017; Hurter et al 2018). Zero observations in each of the parts of the defined composition will be replaced by plausible small values using the log-ratio Expectation-Maximisation algorithm (Rasmussen et al 2020). We will then test the association between sleep (log-ratio) and time spent in each of the rest of the components during awake time. A Dirichlet fixed effects model will then be conducted. 

Also note that we were going to also test all the moderators again according to the protocol.
> The same set of moderators described above can be used here.

Note this is how chatGPT suggests how the model could be implemented:

```
model <- lme4::lmer(sleep_log_ratio ~ sedentary_behavior + light_physical_activity + moderate_vigorous_physical_activity + (1|studyid etc...), data = fixed_effects_data)

```

**Comment by conig** [comment]
@tarensanders correct me if I'm wrong, but for this we agreed that the protocol had been misspecified and the intended analysis was not possible. Accordingly, we'll label a protocol violation and close?

**Comment by tarensanders** [comment]
Agree.
