### ISSUE TITLE
Implement longitudinal cluster analysis

### ISSUE THREAD

**Issue by conig** [Motivation-and-Behaviour/sleepIPD_analysis#61]
> Finally, we will use a cluster analysis of longitudinal data (e.g.,k-means, multiple trajectory analysis) to test whether different sleep, physical activity and sedentary behaviour clusters emerge from the data (Research Question 1).

This is in the protocol, although I can't see a clear link to research question 1:
> 1. Do individuals who are more physically active have better sleep duration and sleep quality?

I'm not quite sure how we would need to set up data for this. I would imagine we'd have one row per person, and then all measurement day variables as columns?

**Comment by tarensanders** [comment]
I think this was probably a suggestion from a contributor, and shouldn't have been included. 

Elsewhere in the protocol we say that we only take baseline data from multi-timepoint studies, so the only way to make 'longitudinal' data is from the sequential days of accelerometry. A trajectory makes no sense when the length of the longitudinal data is a week.

It probably would not be too hard to do k-means or something to describe some low/high pa/sleep groups, but... it doesn't really address a research question so I don't know that it's worth it.

**Comment by conig** [comment]
I agree, I'll label it as a protocol violation and remove it from the milestone.
