### ISSUE TITLE
Implement latent variable approach

### ISSUE THREAD

**Issue by conig** [Motivation-and-Behaviour/sleepIPD_analysis#62]
> Partial least square regression or the creation of a sleep health index will be used to model the relationship between different sleep dimensions (i.e., sleep duration, sleep, efficiency etc.) and physical activity

This last line in the analytic section of the protocol suggests that rather than looking at finite sleep dimensions we'd use an index, or Partial Least Squares regression which would create latent variables from each metric, and then look at the relationship.

**Comment by conig** [comment]
I think creating an index for sleep and PA, which will just be factor analysis for each is going to be the path of least resistence here.

**Comment by conig** [comment]
I take this back, doesn't look like it's really a thing, and so we would need to validate any index we come up with. For this reason, I think risky to do. We would be in a similar situation with any latent variable approach. It's one thing to get a model to fit a latent sleep index, but another to ensure that latent factor is meaningful. For instance, does it make sense to average what time you go to sleep and how long you sleep? We would need to first create defendable scales for each variable where higher scores are better. We might be better off just to be in violation of the protocol on this point.

**Comment by tarensanders** [comment]
Agree - I vote for this being a protocol violation because there's no existing valid method. The results for what makes up the components are more interesting anyway
