### ISSUE TITLE
Improve pipeline stability for final run

### ISSUE THREAD

**Issue by tarensanders** [Motivation-and-Behaviour/sleepIPD_analysis#72]
Each of the targets that produces a model list takes ~1min on my machine, and presumably much longer once we have 50 imps and a full size dataset. There's an advantage to making sure that those can be run in parallel. At the same time, the use for FutureMice creates clashes when it tries to do the imps when the workers already exist.

Going to make a couple of minor tweaks to make this run better on the HPC:

- [x] Set `future::plan(future.callr::callr)` instead of "multisession". See [this discussion](https://github.com/ropensci/targets/discussions/543) for why that is, but TL;DR is the workers aren't created until they are needed.
- [x] Set `deployment = "main"` for data_imp so that there are no workers running when it starts
- [ ] See if we can reduce the number of packages loaded in `packages.R`. This gets sourced for every worker.

Some additional things we could consider:

* Setting up a free tier AWS or GCP and pushing the object from data_imp to a cloud service. As long as we also push `_targets/meta/meta` to github too, we can then have the pipeline on our local machines and just pull the very long running target from the cloud (assuming we don't change anything downstream).

**Comment by conig** [comment]
@tarensanders 
RE:
> See if we can reduce the number of packages loaded in packages.R. This gets sourced for every worker.

Ideally we would only load data.table and some select tidyverse packages as needed. The rest we can use package::fn()

We coud replace load_packages() command with a call to 
```
tar_option_set(packages = c("data.table", "magrittr"))
```

**Comment by tarensanders** [comment]
> Ideally we would only load data.table and some select tidyverse packages as needed. The rest we can use package::fn()

Agree... but do we really want to go back and change that everywhere :sweat_smile:

**Comment by conig** [comment]
I think with GPT wouldn't take more than 1hr to sniff them all out @tarensanders
