### ISSUE TITLE
Do we need to do anything about suspicious kurtosis values?

### ISSUE THREAD

**Issue by conig** [Motivation-and-Behaviour/sleepIPD_analysis#74]
We're tabulating skew and kurtosis for all models in supplementary material. Some kurtosis values are extreme, which could suggest a need to transform variables or inspect convergence further. We must determine whether to address this before using the complete dataset. These values may result from using the smaller data-holdout or indicate something more systematic, such as overfitting or a need to transform variables.

E.g.

![image](https://user-images.githubusercontent.com/12742211/228139995-586d306d-452c-4748-ac81-f7c71d8294dc.png)

**Comment by tarensanders** [comment]
This has calmed way down since fixing the imputations.

![image](https://user-images.githubusercontent.com/20055916/228780370-57b911f4-c5b3-48de-a97b-e1343771c205.png)

All the really large ones ($>|10|$) seem to be when PA volume is the outcome. Let's see if Phil has any concerns

**Comment by tarensanders** [comment]
Try a log transformation of the PA volume variable. With multiverse, we'll do it both ways

**Comment by conig** [comment]
Log-transforming PA_volume has helped, but we still have negative kurtosis values:

![image](https://user-images.githubusercontent.com/12742211/229940904-eafc7a68-2072-4b3b-a7cf-211bc30149a7.png)

**Comment by conig** [comment]
As discussed, kurtosis values were being calculated incorrectly with 3 - kurtosis, instead of kurtosis - 3. Now all positive due to that change.
