### ISSUE TITLE
Implausible imputed values

### ISSUE THREAD

**Issue by tarensanders** [Motivation-and-Behaviour/sleepIPD_analysis#77]
So this would explain #74, and probably the convergence issues.

It's a little hard to see the observed values, but the below still highlights the problem.

![density](https://user-images.githubusercontent.com/20055916/228510455-c2f3760f-4926-4e35-badc-02360652db20.png)

The imputed values for some of these are just wild. Negative values for sleep_duration and pa_volume (where none are observed) and just some truly mental stuff for wakeup variables.

I'm not totally sure why this is happening. My only guess is that https://github.com/Motivation-and-Behaviour/sleepIPD_analysis/blob/1cc682e69ca0c6e011409846be4f20e99ac55493/R/make_data_imp.R#L61 forces a normal distribution for non-normally distributed variables, but when I look at the method (`data_imp$method`) everything is"pmm".

I think the solution could be as simple as just constraining the values in post (per https://www.gerkovink.com/miceVignettes/Passive_Post_processing/Passive_imputation_post_processing.html). Will take a look tomorrow. Any thoughts on this @conig?

**Comment by conig** [comment]
Ouch. Very good catch. We will also want to check if there's issues with convergence in the imputation process.

**Comment by tarensanders** [comment]
Yeah good suggestion.

I know you spent a while working on the multilevel imputation stuff. Is there a reason to choose "2l.norm" over "2l.pmm" given how weird the distributions are? Or, am I just misunderstanding [this](https://stefvanbuuren.name/fimd/sec-multioutcome.html)?

**Comment by conig** [comment]
No 2l.pmm was my preference but it relies on miceadds and I was having trouble getting it working. I can have another look today.

**Comment by tarensanders** [comment]
Closed in #79
