### ISSUE TITLE
There are nine imputations despite being set to three.

### ISSUE THREAD

**Issue by conig** [Motivation-and-Behaviour/sleepIPD_analysis#86]
Something interesting is happening in the ibind loop which makes the number of imputations which starts at 3, turn into 9.
![image](https://user-images.githubusercontent.com/12742211/229944032-4fe85164-3203-443d-9496-c8271f1da3a9.png)

```
Browse[1]> class(imp)
[1] "mids"
Browse[1]> imp$m
[1] 9
```

**Comment by tarensanders** [comment]
Oh I can see what I've done wrong. I'll fix this in the PR with log PA.
